### PR TITLE
Fix enum serialization in rails 4.2

### LINKED ISSUE #798: Bug with enum / enums
Hi,
I have a bug with `enums` and `paper_trail`. I will explain the bug with a dummy example.

```ruby
# We have this model `models/post.rb`
class Post < ActiveRecord::Base
  has_paper_trail
  enum kind: { document: 0, newspaper: 1 }
end
```

```ruby
# We create a post
@post = Post.create(title: "Hello world", kind: :document)

# We update the post for set the enum `kind` to `newspaper`
@post.update_attribute(kind: :newspaper)

# We print the versions we have (only for more informatión)
@post.versions
# return: 
[

    [0] <PaperTrail::Version:0x00558ca746a800> {
                    :id => 3,
             :item_type => "Post",
               :item_id => 916,
                 :event => "create",
             :whodunnit => "684",
                :object => "---\nid: 916\nuser_id: 739\ntitle: 'Hello world'\nkind: \n...",
            :created_at => Mon, 09 May 2016 16:15:55 UTC +00:00,
        :transaction_id => 3
    },
    [1] <PaperTrail::Version:0x00558ca746a6c0> {
                    :id => 4,
             :item_type => "Post",
               :item_id => 916,
                 :event => "update",
             :whodunnit => "684",
                :object => "---\nid: 916\nuser_id: 739\ntitle: 'Hello world'\nkind: \n...",
            :created_at => Mon, 09 May 2016 16:16:15 UTC +00:00,
        :transaction_id => 4
    }
]

# We check previous version
@old_version = @post.previous_version
# return:
<Post:0x00558ca743fad8> {
                    :id => 916,
               :user_id => 739
                 :title => 'Hello world',
                  :kind => nil, # this needs to be "newspaper"
            :created_at => Mon, 09 May 2016 16:15:55 UTC +00:00,
            :updated_at => Mon, 09 May 2016 16:16:05 UTC +00:00
}
```

**Some extra info**

- Ruby 2.2.5
- Rails 4.2.6
- PostgreSQL 9.5.2
- gem PaperTrail 5.0.1 with **Associations** (`--with-associations`)

### PR DESCRIPTION
**Pull request by jaredbeck**
Fixes #798

Our test suite has one model that tests enums, PostWithStatus. Its
spec did not cover `touch_with_version`. Somehow, probably during
our upgrade to rails 5, we broke `touch_with_version` for enums.
Unlike other methods, when an enum arrives at
`CastAttributeSerializer#serialize` during `touch_with_version`, it
is already a number. We assumed it was always a string.

This is sort of a hack, just handling both strings and numbers in
`#serialize`. I'd rather figure out how a number got to `#serialize`
in the first place. However, a hack is acceptable, as it's only
for rails 4.2, and the hack will eventually be deleted when we
drop support for 4.2.

### CODE REVIEW

File: lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb [hunk 1]
```diff
@@ -34,8 +34,13 @@ def initialize(klass)
         end
 
         def serialize(attr, val)
-          val = defined_enums[attr][val] if defined_enums[attr]
-          @klass.type_for_attribute(attr).type_cast_for_database(val)
+          castable_val = val
+          if defined_enums[attr]
+            # `attr` is an enum. Find the number that corresponds to `val`. If `val` is
+            # a number already, there won't be a corresponding entry, just use `val`.
+            castable_val = defined_enums[attr][val] || val
```
Comment (batter) [inline lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb]: Don't think you need the || clause here if your comment is correct since you already assigned val on line 37

Comment (jaredbeck) [inline lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb]: I think we do need the disjunction, otherwise `castable_val` could be incorrectly set to `nil`.

**Comment by jaredbeck** [comment]
Looks like build 1162 (https://travis-ci.org/airblade/paper_trail/builds/152138082) failed because the table under test (`post_with_statuses`) lacked timestamp columns. I keep forgetting that `touch_without_version` requires timestamps. We should probably raise an error instead of failing silently.

Hmmm, still failing on AR 5 / MySQL .. not sure why. Any ideas?

**Comment by jaredbeck** [comment]
> Hmmm, still failing on AR 5 / MySQL .. not sure why. Any ideas? MySQL does have issues with fractional seconds precision .. but I'm not sure ..

Yeah, it was probably a MySQL fractional seconds issue. Adding a `Timecop.travel 1.second.since` seems to have fixed it.

Look good to you, Ben?

File: lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb (hunk 1 above)
Comment (batter) [inline lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb]: Sorry for the delayed response, but if desirable you could condense the code like so:

```ruby
castable_val = defined_enums[attr] && defined_enums[attr][val]
castable_val ||= val
```

The way you have it may be preferable since it allows for the more explicit comment.

**Comment by batter** [comment]
👍

File: lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb (hunk 1 above)
Comment (jaredbeck) [inline lib/paper_trail/attribute_serializers/cast_attribute_serializer.rb]: That looks fine (the `||=` style), Ben. As long as we can keep the comment, I have no preference.
